name 'hw_cookbooks_campfire_handler'
maintainer       'Heavy Water Ops, LLC'
maintainer_email 'support@hw-ops.org'
license          'Apache-2.0'
description      'Installs and configures the chef campfire handler gem'
version          '0.1'
